drop table if exists todo;
create table todo (
                       id bigint generated by default as identity,
                       content varchar(2000),
                       done boolean,
                       created_at timestamp,
                       updated_at timestamp,
                       primary key (id)
);

insert into todo (content, done, created_at)
VALUES ('snsform-eas 세금계산서 연동하기', false, now()),
       ('테크데이 webflux 발표 준비', false, now());